"""initial schema

Revision ID: 2dae7dc8dd42
Revises: 
Create Date: 2026-02-14 16:08:45.153897
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dae7dc8dd42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_description', sa.String(length=500), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('permissions',
    sa.Column('codename', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_codename'), 'permissions', ['codename'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('treatment_machines',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('machine_type', sa.Enum('linac', 'cobalt', 'cyberknife', 'tomotherapy', 'proton', name='machine_type'), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('dicom_ae_title', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('active', 'maintenance', 'decommissioned', name='machine_status'), nullable=False),
    sa.Column('available_energies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_mlc', sa.Boolean(), nullable=False),
    sa.Column('mlc_model', sa.String(length=100), nullable=True),
    sa.Column('mlc_num_leaf_pairs', sa.Integer(), nullable=True),
    sa.Column('mlc_leaf_widths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_gantry_speed', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_dose_rate', sa.Integer(), nullable=True),
    sa.Column('has_cbct', sa.Boolean(), nullable=False),
    sa.Column('has_epid', sa.Boolean(), nullable=False),
    sa.Column('has_kvkv', sa.Boolean(), nullable=False),
    sa.Column('has_surface_guidance', sa.Boolean(), nullable=False),
    sa.Column('last_qa_date', sa.Date(), nullable=True),
    sa.Column('next_qa_date', sa.Date(), nullable=True),
    sa.Column('commissioning_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('professional_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'locked', name='user_status'), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('electronic_signatures',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meaning', sa.Enum('approval', 'review', 'verification', 'authorization', 'acknowledgment', name='signature_meaning'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('signature_hash', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('mrn', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'other', 'unknown', name='sex'), nullable=False),
    sa.Column('phone_primary', sa.String(length=30), nullable=True),
    sa.Column('phone_secondary', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('primary_oncologist_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dicom_patient_id', sa.String(length=64), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_oncologist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_last_name'), 'patients', ['last_name'], unique=False)
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.create_table('qa_checklists',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checklist_type', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['treatment_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['treatment_machines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('tolerance_tables',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('gantry_angle_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('collimator_angle_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('couch_angle_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('couch_vertical_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('couch_lateral_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('couch_longitudinal_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('jaw_x1_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('jaw_x2_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('jaw_y1_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('jaw_y2_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('mlc_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('energy_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dose_rate_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('mu_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('wedge_angle_tol', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('custom_tolerances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['treatment_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('patient_allergies',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.String(length=200), nullable=False),
    sa.Column('reaction', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_diagnoses',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('laterality', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_identifiers',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(length=50), nullable=False),
    sa.Column('identifier_value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_courses',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Enum('curative', 'palliative', 'prophylactic', 'boost', 'sequential', name='plan_intent'), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['patient_diagnoses.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_courses_patient_id'), 'treatment_courses', ['patient_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=False),
    sa.Column('modality', sa.Enum('photon', 'electron', 'proton', 'brachy', name='modality'), nullable=False),
    sa.Column('technique', sa.Enum('3DCRT', 'IMRT', 'VMAT', 'SRS', 'SBRT', 'TBI', 'TSEI', 'electron', name='technique'), nullable=False),
    sa.Column('total_dose_cgy', sa.Integer(), nullable=False),
    sa.Column('dose_per_fraction_cgy', sa.Integer(), nullable=False),
    sa.Column('num_fractions', sa.Integer(), nullable=False),
    sa.Column('fractions_per_week', sa.Integer(), nullable=False),
    sa.Column('energy', sa.String(length=20), nullable=True),
    sa.Column('prescribed_by_id', sa.UUID(), nullable=False),
    sa.Column('prescribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_signature_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_signature_id'], ['electronic_signatures.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['treatment_courses.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_tasks',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_progress', 'completed', 'blocked', 'cancelled', name='task_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='task_priority'), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('assigned_role_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['treatment_courses.id'], ),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['workflow_tasks.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tasks_patient_id'), 'workflow_tasks', ['patient_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('plan_label', sa.String(length=100), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'reviewed', 'pending_approval', 'approved', 'superseded', 'retired', name='plan_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('sop_instance_uid', sa.String(length=128), nullable=True),
    sa.Column('rt_plan_dicom_path', sa.String(length=500), nullable=True),
    sa.Column('rt_dose_sop_uid', sa.String(length=128), nullable=True),
    sa.Column('rt_struct_sop_uid', sa.String(length=128), nullable=True),
    sa.Column('frame_of_reference_uid', sa.String(length=128), nullable=True),
    sa.Column('plan_geometry', sa.String(length=50), nullable=True),
    sa.Column('treatment_machine_id', sa.UUID(), nullable=True),
    sa.Column('num_beams', sa.Integer(), nullable=True),
    sa.Column('num_fractions_planned', sa.Integer(), nullable=True),
    sa.Column('dicom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_signature_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_signature_id', sa.UUID(), nullable=True),
    sa.Column('physics_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('physics_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('physics_approval_signature_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_signature_id'], ['electronic_signatures.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['treatment_courses.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['physics_approval_signature_id'], ['electronic_signatures.id'], ),
    sa.ForeignKeyConstraint(['physics_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['review_signature_id'], ['electronic_signatures.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treatment_machine_id'], ['treatment_machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sop_instance_uid')
    )
    op.create_index(op.f('ix_treatment_plans_prescription_id'), 'treatment_plans', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_status'), 'treatment_plans', ['status'], unique=False)
    op.create_table('fractions',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('fraction_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'partially_treated', 'not_treated', 'cancelled', name='fraction_status'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('treated_date', sa.Date(), nullable=True),
    sa.Column('treated_by_id', sa.UUID(), nullable=True),
    sa.Column('planned_dose_cgy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('delivered_dose_cgy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cumulative_dose_cgy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['treated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fractions_prescription_id'), 'fractions', ['prescription_id'], unique=False)
    op.create_table('plan_beams',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('beam_number', sa.Integer(), nullable=False),
    sa.Column('beam_name', sa.String(length=100), nullable=True),
    sa.Column('beam_type', sa.String(length=50), nullable=False),
    sa.Column('radiation_type', sa.String(length=50), nullable=False),
    sa.Column('treatment_delivery_type', sa.String(length=50), nullable=True),
    sa.Column('energy_mev', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('energy_label', sa.String(length=20), nullable=True),
    sa.Column('dose_rate_mu_per_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planned_mu', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('num_control_points', sa.Integer(), nullable=True),
    sa.Column('gantry_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gantry_rotation', sa.String(length=20), nullable=True),
    sa.Column('collimator_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('couch_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('couch_vertical', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('couch_lateral', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('couch_longitudinal', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('isocenter_x', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('isocenter_y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('isocenter_z', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jaw_x1', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jaw_x2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jaw_y1', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jaw_y2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('wedge_type', sa.String(length=50), nullable=True),
    sa.Column('wedge_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('bolus_description', sa.String(length=200), nullable=True),
    sa.Column('beam_sequence_order', sa.Integer(), nullable=False),
    sa.Column('dicom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_beams_plan_id'), 'plan_beams', ['plan_id'], unique=False)
    op.create_table('qa_records',
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_pass', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_signature_id', sa.UUID(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['qa_checklists.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['treatment_machines.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ),
    sa.ForeignKeyConstraint(['review_signature_id'], ['electronic_signatures.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('fraction_id', sa.UUID(), nullable=True),
    sa.Column('appointment_type', sa.Enum('treatment', 'simulation', 'consultation', 'follow_up', 'physics_qa', 'plan_review', name='appointment_type'), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'checked_in', 'in_progress', 'completed', 'cancelled', 'no_show', name='appointment_status'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('assigned_therapist_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recurring_group_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('cancelled_by_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_therapist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['treatment_courses.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fraction_id'], ['fractions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_start'), 'appointments', ['scheduled_start'], unique=False)
    op.create_table('beam_control_points',
    sa.Column('beam_id', sa.UUID(), nullable=False),
    sa.Column('control_point_index', sa.Integer(), nullable=False),
    sa.Column('cumulative_meterset_weight', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('gantry_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gantry_rotation_direction', sa.String(length=4), nullable=True),
    sa.Column('collimator_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('jaw_x1', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jaw_x2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jaw_y1', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jaw_y2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mlc_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beam_id'], ['plan_beams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beam_control_points_beam_id'), 'beam_control_points', ['beam_id'], unique=False)
    op.create_table('treatment_sessions',
    sa.Column('fraction_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('tolerance_table_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'checked_in', 'setup', 'imaging', 'treatment', 'completed', 'cancelled', 'interrupted', name='session_status'), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setup_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imaging_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treatment_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treatment_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_therapist_id', sa.UUID(), nullable=True),
    sa.Column('secondary_therapist_id', sa.UUID(), nullable=True),
    sa.Column('supervising_physician_id', sa.UUID(), nullable=True),
    sa.Column('patient_verified', sa.Boolean(), nullable=False),
    sa.Column('patient_verified_by_id', sa.UUID(), nullable=True),
    sa.Column('patient_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('imaging_performed', sa.Boolean(), nullable=False),
    sa.Column('position_correction_applied', sa.Boolean(), nullable=False),
    sa.Column('all_beams_verified', sa.Boolean(), nullable=False),
    sa.Column('all_beams_delivered', sa.Boolean(), nullable=False),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.Column('rt_record_sop_uid', sa.String(length=128), nullable=True),
    sa.Column('rt_record_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fraction_id'], ['fractions.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['treatment_machines.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['patient_verified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ),
    sa.ForeignKeyConstraint(['primary_therapist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['secondary_therapist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervising_physician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tolerance_table_id'], ['tolerance_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_sessions_fraction_id'), 'treatment_sessions', ['fraction_id'], unique=False)
    op.create_index(op.f('ix_treatment_sessions_patient_id'), 'treatment_sessions', ['patient_id'], unique=False)
    op.create_table('beam_delivery_records',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('plan_beam_id', sa.UUID(), nullable=False),
    sa.Column('beam_number', sa.Integer(), nullable=False),
    sa.Column('verification_result', sa.Enum('pass', 'fail', 'override', name='verification_result'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('planned_mu', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('planned_gantry_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('planned_collimator_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('planned_couch_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('planned_energy', sa.String(length=20), nullable=True),
    sa.Column('planned_dose_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planned_jaw_x1', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('planned_jaw_x2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('planned_jaw_y1', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('planned_jaw_y2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_mu', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('actual_gantry_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('actual_collimator_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('actual_couch_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('actual_energy', sa.String(length=20), nullable=True),
    sa.Column('actual_dose_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_jaw_x1', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_jaw_x2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_jaw_y1', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_jaw_y2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_couch_vertical', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_couch_lateral', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_couch_longitudinal', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('deviations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('beam_on_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beam_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beam_hold_count', sa.Integer(), nullable=False),
    sa.Column('beam_interrupted', sa.Boolean(), nullable=False),
    sa.Column('interruption_reason', sa.Text(), nullable=True),
    sa.Column('delivered_dose_cgy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['override_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_beam_id'], ['plan_beams.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['treatment_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beam_delivery_records_session_id'), 'beam_delivery_records', ['session_id'], unique=False)
    op.create_table('rt_images',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('sop_instance_uid', sa.String(length=128), nullable=False),
    sa.Column('series_instance_uid', sa.String(length=128), nullable=True),
    sa.Column('study_instance_uid', sa.String(length=128), nullable=True),
    sa.Column('image_type', sa.Enum('portal', 'cbct', 'kv_kv', 'mv', 'drr', 'surface', name='image_type'), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_time', sa.Time(), nullable=True),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('gantry_angle', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('beam_name', sa.String(length=100), nullable=True),
    sa.Column('image_plane', sa.String(length=50), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('pixel_spacing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('dicom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['treatment_machines.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['treatment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sop_instance_uid')
    )
    op.create_index(op.f('ix_rt_images_patient_id'), 'rt_images', ['patient_id'], unique=False)
    op.create_index(op.f('ix_rt_images_session_id'), 'rt_images', ['session_id'], unique=False)
    op.create_table('image_reviews',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'approved', 'rejected', name='image_review_status'), nullable=False),
    sa.Column('shift_vertical_cm', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shift_lateral_cm', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shift_longitudinal_cm', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rotation_pitch_deg', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rotation_roll_deg', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rotation_yaw_deg', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shifts_applied', sa.Boolean(), nullable=False),
    sa.Column('shifts_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shifts_applied_by_id', sa.UUID(), nullable=True),
    sa.Column('review_type', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['rt_images.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['treatment_sessions.id'], ),
    sa.ForeignKeyConstraint(['shifts_applied_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signature_id'], ['electronic_signatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_reviews')
    op.drop_index(op.f('ix_rt_images_session_id'), table_name='rt_images')
    op.drop_index(op.f('ix_rt_images_patient_id'), table_name='rt_images')
    op.drop_table('rt_images')
    op.drop_index(op.f('ix_beam_delivery_records_session_id'), table_name='beam_delivery_records')
    op.drop_table('beam_delivery_records')
    op.drop_index(op.f('ix_treatment_sessions_patient_id'), table_name='treatment_sessions')
    op.drop_index(op.f('ix_treatment_sessions_fraction_id'), table_name='treatment_sessions')
    op.drop_table('treatment_sessions')
    op.drop_index(op.f('ix_beam_control_points_beam_id'), table_name='beam_control_points')
    op.drop_table('beam_control_points')
    op.drop_index(op.f('ix_appointments_scheduled_start'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('qa_records')
    op.drop_index(op.f('ix_plan_beams_plan_id'), table_name='plan_beams')
    op.drop_table('plan_beams')
    op.drop_index(op.f('ix_fractions_prescription_id'), table_name='fractions')
    op.drop_table('fractions')
    op.drop_index(op.f('ix_treatment_plans_status'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_prescription_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_workflow_tasks_patient_id'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_treatment_courses_patient_id'), table_name='treatment_courses')
    op.drop_table('treatment_courses')
    op.drop_table('patient_identifiers')
    op.drop_table('patient_diagnoses')
    op.drop_table('patient_allergies')
    op.drop_table('user_roles')
    op.drop_table('tolerance_tables')
    op.drop_table('role_permissions')
    op.drop_table('resources')
    op.drop_table('qa_checklists')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_index(op.f('ix_patients_last_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('electronic_signatures')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('treatment_machines')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_codename'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
